% Load the fines generated by ProcessMNIST
raw_train = csvread('training-data.txt');
raw_test = csvread('test-data.txt');

% Create training data set and labels
training_labels = raw_train(:,1);
training_data = raw_train(:,2:end);

% Create test data set and labels
test_labels = raw_test(:,1);
test_data = raw_test(:,2:end);

% Create validation set and labels
val_index = randperm(round(size(test_labels) / 2));
validation_labels = test_labels(val_index);
validation_data = test_data(val_index,:);

% remove validation data from test set
lest_labels(val_index) = [];
test_data(val_index,:) = [];

# Save data to binary MAT file
save -7 handwriting.mat training_labels validation_data validation_labels training_data test_labels test_data
